### ISSUE TITLE
Fingerprint not working since update 20200831

### ISSUE THREAD

**Issue by tioui** [LineageOS/android_device_samsung_gts4lvwifi#1]
Hi,

I have been using LineageOS all summer on my Galaxy Tab s5e (thank you for that) without any problem. The Fingerprint was actually a very useful feature for me. The update 20200831 installed without any problem, but after that, it stopped being able to use the fingerprint functionality. I see in the historics that you have update the fingerprint build to Q based build. Is it possible that this broke something?

I have official LineageOS without Gapps. Magisk is installed.

If you need me to test something, getting logs or whatever, I have programming experience, so do not hesitate to ask. But if it is possible, I would prefer not having to wipe the tablet.

Thanks again,

Louis M

**Comment by luk1337** [comment]
Follow post #3 in xda thread.

**Comment by tioui** [comment]
Thanks for your quick answer.
This one: https://forum.xda-developers.com/showpost.php?p=83341191&postcount=3
Just to be sure?

**Comment by luk1337** [comment]
aye

**Comment by tioui** [comment]
Odin don't flash the files. Nothin seems to happend on the tablet. Here is the log from Odin:

<ID:0/003> Odin engine v(ID:3.1207)..
<ID:0/003> File analysis..
<ID:0/003> SetupConnection..
<ID:0/003> Initialzation..
<ID:0/003> Get PIT for mapping..
<ID:0/003> Firmware update start..
<ID:0/003> NAND Write Start!! 
<ID:0/003> SingleDownload.
<ID:0/003> abl.elf.lz4
<ID:0/003> Complete(Write) operation failed.
<ID:0/003> 
<ID:0/003> Complete(Write) operation failed.
<OSM> All threads completed. (succeed 0 / failed 1)

**Comment by luk1337** [comment]
can you screenshot odin and preferably also read what's on your screen?

( also if you want more direct communication, join irc channel #titandev @ freenode )

**Comment by tioui** [comment]
Sorry. It does work. I was using an older version of Odin. That's what append when you have to much version of the same application on the same system.

So thank you very much. How can I send you a beer or two?

**Comment by luk1337** [comment]
glad it worked, here's my paypal email ~ ppay.luk1337@gmail.com if you want to go that way.

**Comment by tioui** [comment]
That's fine with me. It is done.

Good day to you.

Louis M
